export const gurdianFormFields = {
  'gurdian-name': '',
  'gurdian-dateOfBirth': '',
  'gurdian-panPekrnNo': '',
  'gurdian-confirmpanPekrnNo': '',
  'gurdian-mobileIsdCode': '',
  'gurdian-primaryMobileNo': '',
  'gurdian-primaryEmail': '',
  // 'gurdian-primaryMobileBelongsTo': 'A',
  // 'gurdian-primaryEmailBelongsTo': 'A',
  'gurdian-grossIncome': '',
  'gurdian-netWorth': '',
  'gurdian-netWorthDate': '',
  'gurdian-sourceOfWealth': '',
  'gurdian-sourceOfWealthOthers': '',
  'gurdian-occupation': '',
  'gurdian-occupationOthers': '',
  'gurdian-pep': '',
  'gurdian-kraAddressType': '',
  'gurdian-taxResidencyFlag': 'N',
  'gurdian-birthCity': '',
  'gurdian-birthCountry': '',
  'gurdian-citizenshipCountry': '',
  'gurdian-nationalityCountry': '',
  // 'gurdian-sequenceNo': 0,
  'gurdian-taxCountry': '',
  'gurdian-taxReferenceNo': '',
  'gurdian-identityType': '',
};
